# Site Settings
title: Maxim and Sian's Wedding
email: maxandsian@gmail.com
description: >
  All things Maxim and Sian's Wedding
baseurl: ""
url: "http://localhost:4000"
github_username:  sianandmaxim
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM